var globalData = [
  {
    "Country": "Afghanistan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Albania",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.345",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Algeria",
    "Name": "Abdelaziz Bouteflika",
    "Position": "President of Algeria",
    "Birth": "Born: 1937 Morocco",
    "Annual": "168000",
    "Monthly": "14000",
    "Weekly": "3230",
    "Daily": "460",
    "Image": "http://www.paywizard.org/main/salary/vip-check/abdelaziz-bouteflika/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Andorra",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Angola",
    "Name": "José Eduardo dos Santos",
    "Position": "President of Angola",
    "Birth": "Born: 1942 Angola",
    "Annual": "81075",
    "Monthly": "6756",
    "Weekly": "1559",
    "Daily": "222",
    "Image": "http://www.paywizard.org/main/salary/vip-check/jose-eduardo-dos-santos/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.427",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Antigua and Barbuda",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Argentina",
    "Name": "Mauricio Macri",
    "Position": "President Argentina",
    "Birth": "Born: 1959 Argentina",
    "Annual": "68630",
    "Monthly": "5719",
    "Weekly": "1320",
    "Daily": "188",
    "Image": "http://www.paywizard.org/main/salary/vip-check/mauricio-macri/picture",
    "Av National Wage (Monthly USD Dollars)": "1108",
    "Gini": "0.412",
    "GiniYear": "2015",
    "WLAVNational": "5,161552347"
  },
  {
    "Country": "Armenia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "471",
    "Gini": "0.313",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Australia",
    "Name": "Malcolm Turnbull",
    "Position": "Prime Minister of Australia",
    "Birth": "Born: 1954, Australia",
    "Annual": "374701",
    "Monthly": "31225",
    "Weekly": "7206",
    "Daily": "1027",
    "Image": "http://www.paywizard.org/main/salary/vip-check/malcolm-turnbull/picture",
    "Av National Wage (Monthly USD Dollars)": "2610",
    "Gini": "0.305",
    "GiniYear": "2006",
    "WLAVNational": "11,96360153"
  },
  {
    "Country": "Austria",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "3437",
    "Gini": "0.2911",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Azerbaijan",
    "Name": "Ilham Aliyev",
    "Position": "President of Azerbaijan",
    "Birth": "Born: 1961 Azerbaijan",
    "Annual": "225000",
    "Monthly": "18750",
    "Weekly": "4326",
    "Daily": "616",
    "Image": "http://www.paywizard.org/main/salary/vip-check/ilham-aliyev/picture",
    "Av National Wage (Monthly USD Dollars)": "596",
    "Gini": "0.337",
    "GiniYear": "2012",
    "WLAVNational": "31,45973154"
  },
  {
    "Country": "Bahamas",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Bahrain",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "917",
    "Gini": "0.39",
    "GiniYear": "2006",
    "WLAVNational": ""
  },
  {
    "Country": "Bangladesh",
    "Name": "Sheikh Hasina",
    "Position": "Prime Minister Bangladesh",
    "Birth": "Born: 1947 Bangladeh",
    "Annual": "9051",
    "Monthly": "754",
    "Weekly": "174",
    "Daily": "25",
    "Image": "http://www.paywizard.org/main/salary/vip-check/sheikh-hasina/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.321",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Barbados",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Belarus",
    "Name": "Alexander Lukashenko",
    "Position": "President of Belarus",
    "Birth": "Born: 1954 Belarus",
    "Annual": "53777",
    "Monthly": "4481",
    "Weekly": "1034",
    "Daily": "147",
    "Image": "http://www.paywizard.org/main/salary/vip-check/alexander-lukashenko/picture",
    "Av National Wage (Monthly USD Dollars)": "959",
    "Gini": "0.2601",
    "GiniYear": "2011",
    "WLAVNational": "4,6725756"
  },
  {
    "Country": "Belgium",
    "Name": "Charles Michel",
    "Position": "Prime Minister Belgium",
    "Birth": "Born: 1975 Belgium",
    "Annual": "259900",
    "Monthly": "21658",
    "Weekly": "4998",
    "Daily": "712",
    "Image": "http://www.paywizard.org/main/salary/vip-check/charles-michel/picture",
    "Av National Wage (Monthly USD Dollars)": "3035",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": "7,136079077"
  },
  {
    "Country": "Belize",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Benin",
    "Name": "Yayi Boni",
    "Position": "President of Benin",
    "Birth": "Born: 1952 Benin",
    "Annual": "29285",
    "Monthly": "2440",
    "Weekly": "563",
    "Daily": "80",
    "Image": "http://www.paywizard.org/main/salary/vip-check/yayi-boni/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.386",
    "GiniYear": "2003",
    "WLAVNational": ""
  },
  {
    "Country": "Bhutan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.387",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Bolivia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.563",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Bosnia and Herzegovina",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "1338",
    "Gini": "0.363",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Botswana",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "996",
    "Gini": "0.614",
    "GiniYear": "1994",
    "WLAVNational": ""
  },
  {
    "Country": "Brazil",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "778",
    "Gini": "0.547",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Brunei",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Bulgaria",
    "Name": "Rosen Plevneliev",
    "Position": "President Bulgaria",
    "Birth": "Born: 1964 Bulgaria",
    "Annual": "35757",
    "Monthly": "2980",
    "Weekly": "688",
    "Daily": "98",
    "Image": "http://www.paywizard.org/main/salary/vip-check/rosen-plevneliev/picture",
    "Av National Wage (Monthly USD Dollars)": "750",
    "Gini": "0.336",
    "GiniYear": "2012",
    "WLAVNational": "3,973333333"
  },
  {
    "Country": "Burkina Faso",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.398",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Burundi",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.333",
    "GiniYear": "2006",
    "WLAVNational": ""
  },
  {
    "Country": "Cambodia",
    "Name": "Hun Sen",
    "Position": "Prime Minister Cambodia",
    "Birth": "Born: 1952 Cambodia",
    "Annual": "13483",
    "Monthly": "1124",
    "Weekly": "259",
    "Daily": "37",
    "Image": "http://www.paywizard.org/main/salary/vip-check/hun-sun/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.36",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Cameroon",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.389",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Canada",
    "Name": "Justin Trudeau",
    "Position": "Prime Minister Canada",
    "Birth": "Born: 1971 Canada",
    "Annual": "262725",
    "Monthly": "21894",
    "Weekly": "5052",
    "Daily": "720",
    "Image": "http://www.paywizard.org/main/salary/vip-check/justin-trudeau/picture",
    "Av National Wage (Monthly USD Dollars)": "2724",
    "Gini": "0.321",
    "GiniYear": "2005",
    "WLAVNational": "8,037444934"
  },
  {
    "Country": "Cape Verde",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.504",
    "GiniYear": "2001",
    "WLAVNational": ""
  },
  {
    "Country": "Central African Republic",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.563",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Chad",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.398",
    "GiniYear": "2003",
    "WLAVNational": ""
  },
  {
    "Country": "Chile",
    "Name": "Michelle Bachelet",
    "Position": "President Chile",
    "Birth": "Born: 1951 Chile",
    "Annual": "158682",
    "Monthly": "13224",
    "Weekly": "3052",
    "Daily": "435",
    "Image": "http://www.paywizard.org/main/salary/vip-check/michelle-bachelet/picture",
    "Av National Wage (Monthly USD Dollars)": "1021",
    "Gini": "0.495",
    "GiniYear": "2015",
    "WLAVNational": "12,95200784"
  },
  {
    "Country": "China",
    "Name": "Xi Jinping",
    "Position": "President of People's Republic of China",
    "Birth": "Born: 1953 China",
    "Annual": "20806",
    "Monthly": "1734",
    "Weekly": "400",
    "Daily": "57",
    "Image": "http://www.paywizard.org/main/salary/vip-check/xin-jinping/picture",
    "Av National Wage (Monthly USD Dollars)": "656",
    "Gini": "0.614",
    "GiniYear": "2010",
    "WLAVNational": "2,643292683"
  },
  {
    "Country": "Colombia",
    "Name": "Juan Manuel Santos",
    "Position": "President of Colombia",
    "Birth": "Born: 1951 Colombia",
    "Annual": "69585",
    "Monthly": "5799",
    "Weekly": "1338",
    "Daily": "191",
    "Image": "http://www.paywizard.org/main/salary/vip-check/juan-manuel-santos/picture",
    "Av National Wage (Monthly USD Dollars)": "692",
    "Gini": "0.535",
    "GiniYear": "2012",
    "WLAVNational": "8,380057803"
  },
  {
    "Country": "Comoros",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.643",
    "GiniYear": "2004",
    "WLAVNational": ""
  },
  {
    "Country": "Congo",
    "Name": "Joseph Kabila",
    "Position": "President of the Democratic Republic of the Congo",
    "Birth": "Born: 1971, Fizi, Congo-Léopoldville",
    "Annual": "52197",
    "Monthly": "4349",
    "Weekly": "1003",
    "Daily": "143",
    "Image": "http://www.paywizard.org/main/salary/vip-check/joseph-kabila/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.444",
    "GiniYear": "2006",
    "WLAVNational": ""
  },
  {
    "Country": "Costa Rica",
    "Name": "Luis Guillermo Solís",
    "Position": "President Costa Rica",
    "Birth": "Born: 1958 Costa Rica",
    "Annual": "114396",
    "Monthly": "9533",
    "Weekly": "2199",
    "Daily": "313",
    "Image": "http://www.paywizard.org/main/salary/vip-check/luis-guillermo-solis/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.507",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Croatia",
    "Name": "Kolinda Grabar-Kitarović",
    "Position": "President Croatia",
    "Birth": "Born: 1968 Croatia (Yugoslavia)",
    "Annual": "41418",
    "Monthly": "3452",
    "Weekly": "797",
    "Daily": "113",
    "Image": "http://www.paywizard.org/main/salary/vip-check/ivo-josipovic-1/picture",
    "Av National Wage (Monthly USD Dollars)": "1756",
    "Gini": "0.305",
    "GiniYear": "2012",
    "WLAVNational": "1,965831435"
  },
  {
    "Country": "Cuba",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.38",
    "GiniYear": "2002",
    "WLAVNational": ""
  },
  {
    "Country": "Cyprus",
    "Name": "Demetris Christofias",
    "Position": "President Cyprus",
    "Birth": "Born: 1946 Cyprus",
    "Annual": "203785",
    "Monthly": "16982",
    "Weekly": "3918",
    "Daily": "558",
    "Image": "http://www.paywizard.org/main/salary/vip-check/demetris-christofias/picture",
    "Av National Wage (Monthly USD Dollars)": "2605",
    "Gini": "0.31",
    "GiniYear": "2012",
    "WLAVNational": "6,519001919"
  },
  {
    "Country": "Czech Republic",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "1786",
    "Gini": "0.2613",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Denmark",
    "Name": "Lars Løkke Rasmussen",
    "Position": "Prime Minister Denmark",
    "Birth": "Born: 1964 Denmark",
    "Annual": "221444",
    "Monthly": "18454",
    "Weekly": "4259",
    "Daily": "607",
    "Image": "http://www.paywizard.org/main/salary/vip-check/lars-lokke-rasmussen/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.2908",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Djibouti",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.399",
    "GiniYear": "2002",
    "WLAVNational": ""
  },
  {
    "Country": "Dominica",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Dominican Republic",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "462",
    "Gini": "0.463",
    "GiniYear": "2014",
    "WLAVNational": ""
  },
  {
    "Country": "East Timor",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.319",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Ecuador",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.493",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Egypt",
    "Name": "Abdul Fattah Al Sisi",
    "Position": "President Egypt",
    "Birth": "Born: Egypt 1954",
    "Annual": "72000",
    "Monthly": "6000",
    "Weekly": "1384",
    "Daily": "197",
    "Image": "http://www.paywizard.org/main/salary/vip-check/abdul-fattah-al-sisi/picture",
    "Av National Wage (Monthly USD Dollars)": "548",
    "Gini": "0.308",
    "GiniYear": "2008",
    "WLAVNational": "10,94890511"
  },
  {
    "Country": "El Salvador",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.483",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Equatorial Guinea",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Eritrea",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Estonia",
    "Name": "Toomas Hendrik Ilves",
    "Position": "President Estonia",
    "Birth": "Born: 1953 Sweden",
    "Annual": "82177",
    "Monthly": "6848",
    "Weekly": "1580",
    "Daily": "225",
    "Image": "http://www.paywizard.org/main/salary/vip-check/toomas-hendrik-ilves/picture",
    "Av National Wage (Monthly USD Dollars)": "1267",
    "Gini": "0.325",
    "GiniYear": "2012",
    "WLAVNational": "5,404893449"
  },
  {
    "Country": "Ethiopia",
    "Name": "Hailemariam Desalegn",
    "Position": "Prime Minister Ethiopia",
    "Birth": "Born: 1965 Ethiopia",
    "Annual": "44472",
    "Monthly": "3706",
    "Weekly": "855",
    "Daily": "121",
    "Image": "http://www.paywizard.org/main/salary/vip-check/hailemariam-desalegn/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.336",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Fiji",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Finland",
    "Name": "Sauli Niinistö",
    "Position": "President Finland",
    "Birth": "Born: 1948 Finland",
    "Annual": "142380",
    "Monthly": "11865",
    "Weekly": "2738",
    "Daily": "390",
    "Image": "http://www.paywizard.org/main/salary/vip-check/sauli-niinisto/picture",
    "Av National Wage (Monthly USD Dollars)": "2925",
    "Gini": "0.2712",
    "GiniYear": "2013",
    "WLAVNational": "4,056410256"
  },
  {
    "Country": "France",
    "Name": "François Hollande",
    "Position": "President France",
    "Birth": "Born: 1954 France",
    "Annual": "202270",
    "Monthly": "16856",
    "Weekly": "3890",
    "Daily": "554",
    "Image": "http://www.paywizard.org/main/salary/vip-check/francois-hollande/picture",
    "Av National Wage (Monthly USD Dollars)": "2886",
    "Gini": "0.331",
    "GiniYear": "2016",
    "WLAVNational": "5,840609841"
  },
  {
    "Country": "Gabon",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.415",
    "GiniYear": "2005",
    "WLAVNational": ""
  },
  {
    "Country": "Gambia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.473",
    "GiniYear": "2003",
    "WLAVNational": ""
  },
  {
    "Country": "Georgia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "603",
    "Gini": "0.421",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Germany",
    "Name": "Angela Merkel",
    "Position": "Chancellor of Germany",
    "Birth": "Born: Germany 1954",
    "Annual": "249341",
    "Monthly": "20778",
    "Weekly": "4795",
    "Daily": "683",
    "Image": "http://www.paywizard.org/main/salary/vip-check/angela-merkel/picture",
    "Av National Wage (Monthly USD Dollars)": "2720",
    "Gini": "0.3013",
    "GiniYear": "2012",
    "WLAVNational": "7,638970588"
  },
  {
    "Country": "Ghana",
    "Name": "Nana Akufo-Addo",
    "Position": "President Ghana",
    "Birth": "Born: 1944, Ghana",
    "Annual": "37151",
    "Monthly": "3096",
    "Weekly": "714",
    "Daily": "102",
    "Image": "http://www.paywizard.org/main/salary/vip-check/nana-akufo-addo/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.428",
    "GiniYear": "2006",
    "WLAVNational": ""
  },
  {
    "Country": "Greece",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "2300",
    "Gini": "0.343",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Grenada",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Guatemala",
    "Name": "Jimmy Morales",
    "Position": "President Guatemala",
    "Birth": "Born: 1969 Guatemala",
    "Annual": "230364",
    "Monthly": "19197",
    "Weekly": "4430",
    "Daily": "631",
    "Image": "http://www.paywizard.org/main/salary/vip-check/jimmy-morales/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.559",
    "GiniYear": "2006",
    "WLAVNational": ""
  },
  {
    "Country": "Guinea",
    "Name": "Alpha Condé",
    "Position": "President Guinea",
    "Birth": "Born: 1938 Guinea",
    "Annual": "22000",
    "Monthly": "1833",
    "Weekly": "423",
    "Daily": "60",
    "Image": "http://www.paywizard.org/main/salary/vip-check/alpha-conde/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.394",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Guinea-Bissau",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.364",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Guyana",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.432",
    "GiniYear": "1998",
    "WLAVNational": ""
  },
  {
    "Country": "Haiti",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.595",
    "GiniYear": "2001",
    "WLAVNational": ""
  },
  {
    "Country": "Honduras",
    "Name": "Juan Orlando Hernandez",
    "Position": "President Honduras",
    "Birth": "Born: 1968 Honduras",
    "Annual": "42900",
    "Monthly": "3575",
    "Weekly": "825",
    "Daily": "117",
    "Image": "http://www.paywizard.org/main/salary/vip-check/juan-orlando-hernandez/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.58",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Hungary",
    "Name": "Viktor Orbán",
    "Position": "Prime Minister Hungary",
    "Birth": "Born: 1963 Hungary",
    "Annual": "67758",
    "Monthly": "5646",
    "Weekly": "1303",
    "Daily": "186",
    "Image": "http://www.paywizard.org/main/salary/vip-check/viktor-orban/picture",
    "Av National Wage (Monthly USD Dollars)": "1374",
    "Gini": "0.2855",
    "GiniYear": "2012",
    "WLAVNational": "4,109170306"
  },
  {
    "Country": "Iceland",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "2431",
    "Gini": "0.2694",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "India",
    "Name": "Pranab Mukherjee",
    "Position": "President of India",
    "Birth": "Born: 1935 India",
    "Annual": "26940",
    "Monthly": "2245",
    "Weekly": "518",
    "Daily": "74",
    "Image": "http://www.paywizard.org/main/salary/vip-check/pranab-mukherjee/picture",
    "Av National Wage (Monthly USD Dollars)": "295",
    "Gini": "0.339",
    "GiniYear": "2010",
    "WLAVNational": "7,610169492"
  },
  {
    "Country": "Indonesia",
    "Name": "Joko Widodo",
    "Position": "President Indonesia",
    "Birth": "Born: 1961 Indonesia",
    "Annual": "124171",
    "Monthly": "10347",
    "Weekly": "2387",
    "Daily": "340",
    "Image": "http://www.paywizard.org/main/salary/vip-check/joko-widodo-1/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.381",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Iran",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.383",
    "GiniYear": "2005",
    "WLAVNational": ""
  },
  {
    "Country": "Iraq",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Ireland",
    "Name": "Enda Kenny",
    "Position": "Prime Minister Ireland",
    "Birth": "Born: 1951 Ireland",
    "Annual": "209445",
    "Monthly": "17454",
    "Weekly": "4028",
    "Daily": "574",
    "Image": "http://www.paywizard.org/main/salary/vip-check/enda-kenny/picture",
    "Av National Wage (Monthly USD Dollars)": "2997",
    "Gini": "0.298",
    "GiniYear": "2011",
    "WLAVNational": "5,823823824"
  },
  {
    "Country": "Israel",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "1804",
    "Gini": "0.392",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Italy",
    "Name": "Sergio Mattarella",
    "Position": "President Italy",
    "Birth": "Born: 1941, Palermo, Italy",
    "Annual": "259900",
    "Monthly": "21658",
    "Weekly": "4998",
    "Daily": "712",
    "Image": "http://www.paywizard.org/main/salary/vip-check/sergio-mattarella/picture",
    "Av National Wage (Monthly USD Dollars)": "2445",
    "Gini": "0.3516",
    "GiniYear": "2012",
    "WLAVNational": "8,85807771"
  },
  {
    "Country": "Ivory Coast",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.415",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Jamaica",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "1135",
    "Gini": "0.455",
    "GiniYear": "2004",
    "WLAVNational": ""
  },
  {
    "Country": "Japan",
    "Name": "Shinzō Abe",
    "Position": "Prime Minister Japan",
    "Birth": "Born: Japan, 1954",
    "Annual": "202700",
    "Monthly": "16891",
    "Weekly": "3898",
    "Daily": "555",
    "Image": "http://www.paywizard.org/main/salary/vip-check/shinzo-abe/picture",
    "Av National Wage (Monthly USD Dollars)": "2522",
    "Gini": "0.376",
    "GiniYear": "2008",
    "WLAVNational": "6,697462331"
  },
  {
    "Country": "Jordan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.354",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Kazakhstan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "753",
    "Gini": "0.29",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Kenya",
    "Name": "Uhuru Kenyatta",
    "Position": "President Kenya",
    "Birth": "Born: 1961 Kenya",
    "Annual": "160298",
    "Monthly": "13358",
    "Weekly": "3083",
    "Daily": "439",
    "Image": "http://www.paywizard.org/main/salary/vip-check/uhuru-kenyatta/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Kiribati",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Kosovo",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Kuwait",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Kyrgyzstan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "336",
    "Gini": "0.334",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Laos",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.367",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Latvia",
    "Name": "Andris Bērziņš",
    "Position": "President Latvia",
    "Birth": "Born: 1944 Soviet Union (now Latvia)",
    "Annual": "62150",
    "Monthly": "5179",
    "Weekly": "1195",
    "Daily": "170",
    "Image": "http://www.paywizard.org/main/salary/vip-check/andris-berzins/picture",
    "Av National Wage (Monthly USD Dollars)": "1098",
    "Gini": "0.359",
    "GiniYear": "2012",
    "WLAVNational": "4,716757741"
  },
  {
    "Country": "Lebanon",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Lesotho",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.525",
    "GiniYear": "2003",
    "WLAVNational": ""
  },
  {
    "Country": "Liberia",
    "Name": "Ellen Johnson Sirleaf",
    "Position": "President Liberia",
    "Birth": "Born: 1938 Liberia",
    "Annual": "90000",
    "Monthly": "7500",
    "Weekly": "1730",
    "Daily": "246",
    "Image": "http://www.paywizard.org/main/salary/vip-check/ellen-johnson-sirleaf/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.526",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Libya",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Liechtenstein",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Lithuania",
    "Name": "Dalia Grybauskaitė",
    "Position": "President Lithuania",
    "Birth": "Born: 1956 Vilnius, Soviet Union (now Lithuania)",
    "Annual": "352560",
    "Monthly": "29380",
    "Weekly": "6780",
    "Daily": "966",
    "Image": "http://www.paywizard.org/main/salary/vip-check/dalia-grybauskaite/picture",
    "Av National Wage (Monthly USD Dollars)": "1109",
    "Gini": "0.32",
    "GiniYear": "2012",
    "WLAVNational": "26,49233544"
  },
  {
    "Country": "Luxembourg",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "4089",
    "Gini": "0.3479",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Macedonia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "1345",
    "Gini": "0.436",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Madagascar",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.441",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Malawi",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Malaysia",
    "Name": "Najib Razak",
    "Position": "Prime Minister of Malaysia",
    "Birth": "Born: 1953 Malaysia",
    "Annual": "67289",
    "Monthly": "5607",
    "Weekly": "1294",
    "Daily": "184",
    "Image": "http://www.paywizard.org/main/salary/vip-check/najib-razak/picture",
    "Av National Wage (Monthly USD Dollars)": "961",
    "Gini": "0.462",
    "GiniYear": "2009",
    "WLAVNational": "5,834547347"
  },
  {
    "Country": "Maldives",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Mali",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.33",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Malta",
    "Name": "Joseph Muscat",
    "Position": "Prime Minister Malta",
    "Birth": "Born: 1974 Malta",
    "Annual": "57630",
    "Monthly": "4802",
    "Weekly": "1108",
    "Daily": "158",
    "Image": "http://www.paywizard.org/main/salary/vip-check/joseph-muscat/picture",
    "Av National Wage (Monthly USD Dollars)": "1808",
    "Gini": "0.2909",
    "GiniYear": "2012",
    "WLAVNational": "2,655973451"
  },
  {
    "Country": "Marshall Islands",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Mauritania",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.405",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Mauritius",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "783",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Mexico",
    "Name": "Enrique Peña Nieto",
    "Position": "President of Mexico",
    "Birth": "Born: Mexico 1966",
    "Annual": "162703",
    "Monthly": "13559",
    "Weekly": "3129",
    "Daily": "446",
    "Image": "http://www.paywizard.org/main/salary/vip-check/enrique-pena-nieto/picture",
    "Av National Wage (Monthly USD Dollars)": "609",
    "Gini": "0.472",
    "GiniYear": "2010",
    "WLAVNational": "22,26436782"
  },
  {
    "Country": "Micronesia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Moldova",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "438",
    "Gini": "0.33",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Monaco",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Mongolia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "415",
    "Gini": "0.366",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Montenegro",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.286",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Morocco",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.409",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Mozambique",
    "Name": "Filipe Nyusi",
    "Position": "President Mozambique",
    "Birth": "Born: 1959 Mozambique",
    "Annual": "47500",
    "Monthly": "3958",
    "Weekly": "913",
    "Daily": "130",
    "Image": "http://www.paywizard.org/main/salary/vip-check/filipe-nyusi/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.457",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Myanmar",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Namibia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.639",
    "GiniYear": "2004",
    "WLAVNational": ""
  },
  {
    "Country": "Nauru",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Nepal",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.328",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Netherlands",
    "Name": "Mark Rutte",
    "Position": "Prime Minister of the Netherlands",
    "Birth": "Born: 1967 the Netherlands",
    "Annual": "177734",
    "Monthly": "14811",
    "Weekly": "3418",
    "Daily": "487",
    "Image": "http://www.paywizard.org/main/salary/vip-check/mark-rutte/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.2799",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "New Zealand",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "2283",
    "Gini": "0.362",
    "GiniYear": "1997",
    "WLAVNational": ""
  },
  {
    "Country": "Nicaragua",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.34",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Niger",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.34",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Nigeria",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.488",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "North Korea",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Norway",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "3678",
    "Gini": "0.259",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Oman",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Pakistan",
    "Name": "Syed Mamnoon Hussain",
    "Position": "President Pakistan",
    "Birth": "Born: 1940 India",
    "Annual": "9548",
    "Monthly": "796",
    "Weekly": "184",
    "Daily": "26",
    "Image": "http://www.paywizard.org/main/salary/vip-check/syed-mamnoon-hussain/picture",
    "Av National Wage (Monthly USD Dollars)": "255",
    "Gini": "0.3",
    "GiniYear": "2008",
    "WLAVNational": "3,121568627"
  },
  {
    "Country": "Palau",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Palestine",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.355",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Panama",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "831",
    "Gini": "0.519",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Papua New Guinea",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.509",
    "GiniYear": "1996",
    "WLAVNational": ""
  },
  {
    "Country": "Paraguay",
    "Name": "Horacio Cartes",
    "Position": "President Paraquay",
    "Birth": "Born: 1956 Paraguay",
    "Annual": "80550",
    "Monthly": "6713",
    "Weekly": "1549",
    "Daily": "221",
    "Image": "http://www.paywizard.org/main/salary/vip-check/horacio-cartes/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.524",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Peru",
    "Name": "Pedro Pablo Kuczynski",
    "Position": "President Peru",
    "Birth": "Born: 1938, Lima, Peru",
    "Annual": "44628",
    "Monthly": "3719",
    "Weekly": "858",
    "Daily": "122",
    "Image": "http://www.paywizard.org/main/salary/vip-check/pedro-pablo-kuczynski/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.481",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Philippines",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "279",
    "Gini": "0.43",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Poland",
    "Name": "Beata Szydło",
    "Position": "Prime Minister Poland",
    "Birth": "Born: 1963 Poland",
    "Annual": "51233",
    "Monthly": "4269",
    "Weekly": "985",
    "Daily": "140",
    "Image": "http://www.paywizard.org/main/salary/vip-check/beata-szydlo/picture",
    "Av National Wage (Monthly USD Dollars)": "1536",
    "Gini": "0.309",
    "GiniYear": "2012",
    "WLAVNational": "2,779296875"
  },
  {
    "Country": "Portugal",
    "Name": "António Costa",
    "Position": "Prime Minister Portugal",
    "Birth": "Born: 1961, Lisbon, Portugal",
    "Annual": "89173",
    "Monthly": "7431",
    "Weekly": "1715",
    "Daily": "244",
    "Image": "http://www.paywizard.org/main/salary/vip-check/antonio-costa/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.3604",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Qatar",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "1690",
    "Gini": "0.411",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Republic of the Congo",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Romania",
    "Name": "Traian Basescu",
    "Position": "President Romania",
    "Birth": "Born: Romania 1951",
    "Annual": "20163",
    "Monthly": "1680",
    "Weekly": "388",
    "Daily": "55",
    "Image": "http://www.paywizard.org/main/salary/vip-check/traian-basescu/picture",
    "Av National Wage (Monthly USD Dollars)": "954",
    "Gini": "0.332",
    "GiniYear": "2012",
    "WLAVNational": "1,761006289"
  },
  {
    "Country": "Russia",
    "Name": "Vladimir Putin",
    "Position": "President of Russia",
    "Birth": "Born: 1952 Russia",
    "Annual": "135736",
    "Monthly": "11311",
    "Weekly": "2610",
    "Daily": "372",
    "Image": "http://www.paywizard.org/main/salary/vip-check/vladimir-putin/picture",
    "Av National Wage (Monthly USD Dollars)": "1215",
    "Gini": "0.42",
    "GiniYear": "2012",
    "WLAVNational": "9,309465021"
  },
  {
    "Country": "Rwanda",
    "Name": "Paul Kagame",
    "Position": "President Rwanda",
    "Birth": "Born: 1957 Rwanda",
    "Annual": "85000",
    "Monthly": "7083",
    "Weekly": "1634",
    "Daily": "232",
    "Image": "http://www.paywizard.org/main/salary/vip-check/paul-kagame/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.508",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Saint Kitts and Nevis",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Saint Lucia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Saint Vincent and the Grenadines",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Samoa",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "San Marino",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Sao Tome and Principe",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Saudi Arabia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Senegal",
    "Name": "Macky Sall",
    "Position": "Prime Minister Senegal",
    "Birth": "Born: Senegal 1961",
    "Annual": "14941",
    "Monthly": "1245",
    "Weekly": "287",
    "Daily": "40",
    "Image": "http://www.paywizard.org/main/salary/vip-check/macky-sall/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.403",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Serbia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "1058",
    "Gini": "0.296",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Seychelles",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.658",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Sierra Leone",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.354",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Singapore",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "2616",
    "Gini": "0.473",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Slovakia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "1385",
    "Gini": "0.2612",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Slovenia",
    "Name": "Borut Pahor",
    "Position": "Prime Minister Slovenia",
    "Birth": "Born: 1963 Slovenia",
    "Annual": "40680",
    "Monthly": "3390",
    "Weekly": "782",
    "Daily": "111",
    "Image": "http://www.paywizard.org/main/salary/vip-check/borut-pahor/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.2529",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Solomon Islands",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Somalia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "South Africa",
    "Name": "Jacob Zuma",
    "Position": "President of South Africa",
    "Birth": "Born: 1942 South Africa",
    "Annual": "272000",
    "Monthly": "22666",
    "Weekly": "5230",
    "Daily": "745",
    "Image": "http://www.paywizard.org/main/salary/vip-check/jacob-zuma/picture",
    "Av National Wage (Monthly USD Dollars)": "1838",
    "Gini": "0.631",
    "GiniYear": "2009",
    "WLAVNational": "12,33188248"
  },
  {
    "Country": "South Korea",
    "Name": "Park Geun-hye",
    "Position": "President South Korea",
    "Birth": "Born: South Korea 1952",
    "Annual": "178000",
    "Monthly": "14833",
    "Weekly": "3423",
    "Daily": "487",
    "Image": "http://www.paywizard.org/main/salary/vip-check/park-geun-hye/picture",
    "Av National Wage (Monthly USD Dollars)": "2903",
    "Gini": "0.31",
    "GiniYear": "2006",
    "WLAVNational": "5,109541853"
  },
  {
    "Country": "South Sudan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.455",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Spain",
    "Name": "Mariano Rajoy Brey",
    "Position": "Prime Minister of Spain",
    "Birth": "Born: Spain 1955",
    "Annual": "88140",
    "Monthly": "7345",
    "Weekly": "1695",
    "Daily": "241",
    "Image": "http://www.paywizard.org/main/salary/vip-check/mariano-rajoy-brey/picture",
    "Av National Wage (Monthly USD Dollars)": "2352",
    "Gini": "0.35",
    "GiniYear": "2012",
    "WLAVNational": "3,12287415"
  },
  {
    "Country": "Sri Lanka",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.364",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Sudan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.353",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Suriname",
    "Name": "Désiré Delano (Desi) Bouterse",
    "Position": "President of Suriname",
    "Birth": "Born: 1945 Suriname",
    "Annual": "127566",
    "Monthly": "10630",
    "Weekly": "2453",
    "Daily": "349",
    "Image": "http://www.paywizard.org/main/salary/vip-check/desire-delano-desi-bouterse/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.613",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Swaziland",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.515",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Sweden",
    "Name": "Fredrik Reinfeldt",
    "Position": "Prime Minister Sweden",
    "Birth": "Born: 1965 Sweden",
    "Annual": "221864",
    "Monthly": "18489",
    "Weekly": "4267",
    "Daily": "608",
    "Image": "http://www.paywizard.org/main/salary/vip-check/fredrik-reinfeldt/picture",
    "Av National Wage (Monthly USD Dollars)": "3023",
    "Gini": "0.2732",
    "GiniYear": "2012",
    "WLAVNational": "6,116109825"
  },
  {
    "Country": "Switzerland",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.287",
    "GiniYear": "2012",
    "WLAVNational": ""
  },
  {
    "Country": "Syria",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "364",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Taiwan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.327",
    "GiniYear": "2000",
    "WLAVNational": ""
  },
  {
    "Country": "Tajikistan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "227",
    "Gini": "0.308",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Tanzania",
    "Name": "John Magufuli",
    "Position": "President Tanzania",
    "Birth": "Born: Tanzania 1959",
    "Annual": "192000",
    "Monthly": "16000",
    "Weekly": "3692",
    "Daily": "526",
    "Image": "http://www.paywizard.org/main/salary/vip-check/john-magufuli/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.376",
    "GiniYear": "2007",
    "WLAVNational": ""
  },
  {
    "Country": "Thailand",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "489",
    "Gini": "0.394",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Togo",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.393",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Tonga",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Trinidad and Tobago",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.403",
    "GiniYear": "1992",
    "WLAVNational": ""
  },
  {
    "Country": "Tunisia",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.361",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Turkey",
    "Name": "Recep Tayyip Erdoğan",
    "Position": "President Turkey",
    "Birth": "Born: Turkey 1954",
    "Annual": "202352",
    "Monthly": "16863",
    "Weekly": "3891",
    "Daily": "554",
    "Image": "http://www.paywizard.org/main/salary/vip-check/recep-tayyip-erdogan/picture",
    "Av National Wage (Monthly USD Dollars)": "1731",
    "Gini": "0.448",
    "GiniYear": "2006",
    "WLAVNational": "9,741767764"
  },
  {
    "Country": "Turkmenistan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.408",
    "GiniYear": "1998",
    "WLAVNational": ""
  },
  {
    "Country": "Tuvalu",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Uganda",
    "Name": "Yoweri Museveni",
    "Position": "President Uganda",
    "Birth": "Born: 1944 Uganda",
    "Annual": "13000",
    "Monthly": "1083",
    "Weekly": "250",
    "Daily": "35",
    "Image": "http://www.paywizard.org/main/salary/vip-check/yoweri-museveni/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.443",
    "GiniYear": "2009",
    "WLAVNational": ""
  },
  {
    "Country": "Ukraine",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "686",
    "Gini": "0.2455",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "United Arab Emirates",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "United Kingdom",
    "Name": "Theresa May",
    "Position": "Prime Minister of the United Kingdom",
    "Birth": "Born: 1956 UK",
    "Annual": "207836",
    "Monthly": "17320",
    "Weekly": "3997",
    "Daily": "569",
    "Image": "http://www.paywizard.org/main/salary/vip-check/theresa-may/picture",
    "Av National Wage (Monthly USD Dollars)": "3065",
    "Gini": "0.33",
    "GiniYear": "2012",
    "WLAVNational": "5,650897227"
  },
  {
    "Country": "Uruguay",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.386",
    "GiniYear": "2015",
    "WLAVNational": ""
  },
  {
    "Country": "USA",
    "Name": "Donald Trump",
    "Position": "President of the U.S.",
    "Birth": "Born: 1946, Queens, NYC",
    "Annual": "400000",
    "Monthly": "33333",
    "Weekly": "7692",
    "Daily": "1095",
    "Image": "http://www.paywizard.org/main/salary/vip-check/donald-trump/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.469",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Uzbekistan",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.367",
    "GiniYear": "2003",
    "WLAVNational": ""
  },
  {
    "Country": "Vanuatu",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Vatican City",
    "Name": "Francis",
    "Position": "Pope of the Catholic Church",
    "Birth": "Born: 1936 Argentina",
    "Annual": "0",
    "Monthly": "0",
    "Weekly": "0",
    "Daily": "0",
    "Image": "http://www.paywizard.org/main/salary/vip-check/francis/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "",
    "GiniYear": "",
    "WLAVNational": ""
  },
  {
    "Country": "Venezuela",
    "Name": "Nicolas Maduro",
    "Position": "President of Venezuela",
    "Birth": "Born: 1962 Venezuela",
    "Annual": "46893",
    "Monthly": "3907",
    "Weekly": "901",
    "Daily": "128",
    "Image": "http://www.paywizard.org/main/salary/vip-check/nicolas-maduro/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.39",
    "GiniYear": "2011",
    "WLAVNational": ""
  },
  {
    "Country": "Vietnam",
    "Name": "Nguyễn Xuân Phúc",
    "Position": "Prime Minister Vietnam",
    "Birth": "Born: 1954 Vietnam",
    "Annual": "9228",
    "Monthly": "769",
    "Weekly": "177",
    "Daily": "25",
    "Image": "http://www.paywizard.org/main/salary/vip-check/nguyen-xuan-phuc/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.378",
    "GiniYear": "2008",
    "WLAVNational": ""
  },
  {
    "Country": "Yemen",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.377",
    "GiniYear": "2005",
    "WLAVNational": ""
  },
  {
    "Country": "Zambia",
    "Name": "Edgar Lungu",
    "Position": "President Zambia",
    "Birth": "Born: 1956, Ndola, Zambia",
    "Annual": "56000",
    "Monthly": "4666",
    "Weekly": "1076",
    "Daily": "153",
    "Image": "http://www.paywizard.org/main/salary/vip-check/edgar-lungu/picture",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.575",
    "GiniYear": "2010",
    "WLAVNational": ""
  },
  {
    "Country": "Zimbabwe",
    "Name": "",
    "Position": "",
    "Birth": "",
    "Annual": "",
    "Monthly": "",
    "Weekly": "",
    "Daily": "",
    "Image": "",
    "Av National Wage (Monthly USD Dollars)": "",
    "Gini": "0.501",
    "GiniYear": "2006",
    "WLAVNational": ""
  }
]